services:
  - type: web
    name: clinicai-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: GROQ_API_KEY
        value: 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
      - key: ULTRAMSG_INSTANCE
        value: instance166153
      - key: ULTRAMSG_TOKEN
        value: ch512e62wj5hxj36
      - key: DOCTOR_NUMBER
        value: "916205131181"
